import type {
  AuditEvent,
  AuditKind,
  PendingDoctor,
  PendingPatient,
} from "./types";

export const SA_PROVINCES_HEALTH = [
  { name: "Gauteng", status: "green" as const, sessions: 1247, latency: 98 },
  { name: "KwaZulu-Natal", status: "green" as const, sessions: 892, latency: 124 },
  { name: "Western Cape", status: "green" as const, sessions: 1102, latency: 102 },
  { name: "Eastern Cape", status: "amber" as const, sessions: 234, latency: 287 },
  { name: "Free State", status: "green" as const, sessions: 318, latency: 156 },
  { name: "Limpopo", status: "amber" as const, sessions: 156, latency: 312 },
  { name: "Mpumalanga", status: "green" as const, sessions: 287, latency: 168 },
  { name: "Northern Cape", status: "green" as const, sessions: 89, latency: 198 },
  { name: "North West", status: "green" as const, sessions: 203, latency: 174 },
];

export const PENDING_DOCTORS: PendingDoctor[] = [
  {
    id: "pd1",
    name: "Dr. K. Adams",
    specialty: "Paediatrician",
    hpcsa: "MP088234",
    hospital: "Netcare Sunninghill",
    submitted: "2 days ago",
  },
  {
    id: "pd2",
    name: "Nurse L. Zulu",
    specialty: "ICU Nurse (SANC)",
    hpcsa: "SANC-449821",
    hospital: "Chris Hani Baragwanath",
    submitted: "5 hours ago",
  },
  {
    id: "pd3",
    name: "Dr. M. Naidoo",
    specialty: "Dermatologist",
    hpcsa: "MP091122",
    hospital: "Netcare Sunninghill",
    submitted: "1 day ago",
  },
];

export const PENDING_PATIENTS: PendingPatient[] = [
  {
    id: "pp1",
    name: "M. Khumalo",
    idType: "SA ID",
    hospital: "Chris Hani Baragwanath",
    submitted: "1 hour ago",
  },
  {
    id: "pp2",
    name: "P. Sithole",
    idType: "Passport",
    hospital: "Charlotte Maxeke",
    submitted: "3 hours ago",
  },
  {
    id: "pp3",
    name: "L. Botha (minor)",
    idType: "Birth cert",
    hospital: "Groote Schuur",
    submitted: "Yesterday",
  },
  {
    id: "pp4",
    name: "T. Molefe",
    idType: "Refugee permit",
    hospital: "Charlotte Maxeke",
    submitted: "2 days ago",
  },
];

export const AUDIT_EXTENDED: AuditEvent[] = [
  {
    id: "a-1",
    actor: "Dr. Mokoena",
    action: "submitted patient record",
    target: "Patient #1847",
    time: "2 min ago",
    kind: "auth",
    ip: "41.13.22.108",
    device: "iPhone · Safari 17",
    hash: "0x7af3…b9c2",
  },
  {
    id: "a-2",
    actor: "System",
    action: "flagged unusual access pattern",
    target: "API Gateway",
    time: "8 min ago",
    kind: "system",
    ip: "196.21.14.55",
    device: "Server · Ubuntu 22.04",
    hash: "0x9d2e…1f8a",
  },
  {
    id: "a-3",
    actor: "Admin",
    action: "verified hospital",
    target: "Chris Hani Baragwanath",
    time: "14 min ago",
    kind: "verify",
    ip: "102.222.86.41",
    device: "MacBook · Chrome 124",
    hash: "0x4c81…6e30",
  },
  {
    id: "a-4",
    actor: "Dr. Dlamini",
    action: "submitted lab results",
    target: "Patient #2201",
    time: "22 min ago",
    kind: "create",
    ip: "197.97.42.12",
    device: "iPhone · Safari 17",
    hash: "0x2b5f…a714",
  },
  {
    id: "a-5",
    actor: "System",
    action: "backup completed",
    target: "Database Cluster",
    time: "45 min ago",
    kind: "system",
    ip: "154.66.18.220",
    device: "Server · Ubuntu 22.04",
    hash: "0x8e0c…d239",
  },
  {
    id: "a-6",
    actor: "Admin",
    action: "rejected registration",
    target: "Pending #882",
    time: "1 hr ago",
    kind: "delete",
    ip: "41.13.22.108",
    device: "MacBook · Chrome 124",
    hash: "0x1a4b…9f72",
  },
  {
    id: "a-7",
    actor: "Dr. Naidoo",
    action: "updated prescription",
    target: "Patient #3304",
    time: "1.5 hr ago",
    kind: "edit",
    ip: "196.21.14.55",
    device: "Server · Ubuntu 22.04",
    hash: "0x6c33…8e51",
  },
];

export const SYSTEM_METRICS = {
  uptime: 99.98,
  apiLatency: 142,
  apiP50: 98,
  apiP95: 287,
  dhis2LastSync: "12 min ago",
  dhis2Queue: 8,
  dhis2Status: "in-sync" as const,
  dbPool: 47,
  dbPoolMax: 100,
  dbSize: "847 GB",
  dbStatus: "healthy" as const,
  activeSessions: 4283,
  cpuLoad: 38,
  memoryLoad: 54,
  diskLoad: 71,
};

export const API_RESPONSE_TREND = [
  { t: "00:00", ms: 95 },
  { t: "04:00", ms: 88 },
  { t: "08:00", ms: 142 },
  { t: "12:00", ms: 168 },
  { t: "16:00", ms: 187 },
  { t: "20:00", ms: 124 },
  { t: "now", ms: 142 },
];
